[package]
name = "stocklib"
version = "0.1.1"
authors = ["Kai Sickeler <k.sickeler@gmail.com>"]

[dependencies]
select = "0.4.2"
reqwest = "0.9.0"
regex = "0.2.2"
nix = "0.9.0"
chrono = "0.4"
quick-error = "*"
